// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMiaO6CyTRP1T1XVmIfzDGr5NdUi1feBE',
    appId: '1:49321399584:web:bd7e6fa33d5e1974d9b345',
    messagingSenderId: '49321399584',
    projectId: 'foodielife-49f2d',
    authDomain: 'foodielife-49f2d.firebaseapp.com',
    storageBucket: 'foodielife-49f2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEwbEN1uT3MdRyFIP6XkFS4B5QKNC9s5Y',
    appId: '1:49321399584:android:a634d3bf356978e2d9b345',
    messagingSenderId: '49321399584',
    projectId: 'foodielife-49f2d',
    storageBucket: 'foodielife-49f2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVTCKZr7sNw5G0VuUmx1RtC8pJPeMHmZ0',
    appId: '1:49321399584:ios:1369175690d54b5fd9b345',
    messagingSenderId: '49321399584',
    projectId: 'foodielife-49f2d',
    storageBucket: 'foodielife-49f2d.appspot.com',
    iosBundleId: 'com.example.foodeiLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVTCKZr7sNw5G0VuUmx1RtC8pJPeMHmZ0',
    appId: '1:49321399584:ios:5b759e622f838ccad9b345',
    messagingSenderId: '49321399584',
    projectId: 'foodielife-49f2d',
    storageBucket: 'foodielife-49f2d.appspot.com',
    iosBundleId: 'com.example.foodeiLife.RunnerTests',
  );
}
